# Defines object locations as [x, y, theta]
location1: [2.0, 0, 0]
#location1: [2.0, 0, 1.57]
location2: [2.0, -2, 0]
#location2: [2.0, -2, 3.14]
location3: [0.0, -2, 0]
#location3: [0.0, -2, -1.57]
location4: [0.0, 0, 0]
#location4: [0.0, 0, 0]